### ISSUE TITLE
Sound settings in the in game menu

### ISSUE THREAD

**Issue by Zoap** [AoTTG-2/AoTTG-2#768]
**How will this enhancement improve the game?**

Players need to be able to change the volume in game to their liking.

**Before you start.**

- [ ] Make sure #604 is done.

- [x] Make sure #691 is done.
- [ ] Make sure #767 is done.

**Describe the solution you'd like**

A settings button in the in game menu that leads to the sound settings

- [ ] Volume slider, master volume (changes all volume)
- [ ] Volume slider, music volume (changes music volume)
- [ ] Volume slider, effects volume. (changes sfx volume, just setup the slider for this, it doesn't have to do anything)

**Contributor instructions (Do not modify)**

Determine if the enhancement is compatible with existing features
If the idea is denied, please provide a reason and close the issue. If the idea is accepted, consult your team to do an estimation of effort. Remove the [PROPOSAL] name and label.
Move the issue to the Future Milestone. On rare exceptions an issue may be moved to Release if there's sufficient upvotes.
Once the issue matches the current milestone, follow development procedures.
